# Generated by Django 5.0 on 2024-03-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        ('team', '0002_remove_teammodel_projects_remove_teammodel_tasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='user',
            new_name='admin_name',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='tasks',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='task_name',
            field=models.ManyToManyField(blank=True, to='tasks.taskmodel'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.teammodel'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='abandon_reason',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='daily_target',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('ONGOING', 'Ongoing'), ('ABANDON', 'Abandon'), ('COMPLETED', 'Completed')], max_length=20),
        ),
    ]
