# Generated by Django 5.0 on 2024-03-19 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='schedulemodel',
            name='admin_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Ongoing', 'Ongoing'), ('Abandon', 'Abandon'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
    ]
